- packages/server/markup/admin.js
- packages/server/routes/page.js
- packages/server/routes/view.js
view edit to bar to avoid card
> view edit to bar to avoid card

- README.md
- deploy/examples/test/docker-compose.yml
- deploy/examples/test/docker-entrypoint-initdb.sql
delivers case 2 from #390 :
> a non-programmer who just wants to run Saltcorn, but for whatever reason they don't want to use the SQLite database.
> Docker compose standalone

- packages/saltcorn-cli/src/commands/run-tests.js
RunTestsCommand supports --watch and --watchAll instead of --forever.
jest will launch in an interactive watch mode and reruns on changes.
--watch reruns tests related to a changed file
--watchAll reruns all tests
> Added --watch / --watchAll to run-tests and removed --forever

- packages/saltcorn-data/db/index.ts
- packages/saltcorn-data/models/role.ts
- packages/saltcorn-markup/layout.ts
- packages/saltcorn-markup/table.ts
- packages/saltcorn-markup/tabs.ts
- packages/server/routes/homepage.js
- packages/server/routes/index.js
The better-docs typescript plugin does not support all language features.
.ts Files with unsupported features show up in the global category.
> fixed jsdocs

- packages/saltcorn-data/models/backup.ts
- packages/saltcorn-data/models/field.ts
- packages/saltcorn-data/models/form.ts
- packages/saltcorn-data/models/table.ts
- packages/saltcorn-data/models/view.ts
- packages/saltcorn-data/models/workflow.ts
- packages/saltcorn-data/package.json
- packages/saltcorn-types/base_types.ts
- packages/saltcorn-types/common_types.ts
- packages/saltcorn-types/model-abstracts/abstract_field.ts
- packages/saltcorn-types/model-abstracts/abstract_table.ts
- packages/saltcorn-types/model-abstracts/abstract_workflow.ts
* migrated view.js to typescript
* added more types in backup.js
* added all types in 'saltcorn-types' that
the tsc build requires
> migrated view.js

- Dockerfile.release
- The installation fails at the sqlite3 build with node 16
> downgraded to node 14

- packages/saltcorn-data/base-plugin/actions.js
typedoc determines it on its own
> removed failing type

- packages/saltcorn-data/base-plugin/viewtemplates/feed.js
- packages/saltcorn-data/base-plugin/viewtemplates/list.js
- packages/saltcorn-data/base-plugin/viewtemplates/listshowlist.js
- packages/saltcorn-mobile-app/.gitignore
- packages/saltcorn-mobile-app/www/config
- packages/saltcorn-mobile-app/www/js/utils/iframe_view_utils.js
- packages/saltcorn-mobile-builder/src/commands/build-app.ts
There is still a problem with the paging in listshowlist.
I could send the paging parameters from here to the subview:
https://github.com/christianhugoch/saltcorn/blob/e294c825d29191e9cb1bfe94125718c125b11817/packages/saltcorn-data/base-plugin/viewtemplates/listshowlist.js#L230
but I believe if there are multiple subviews, we need a way to identify which should receive them.
> added paging, fixed link path for sbadmin2

- packages/saltcorn-data/base-plugin/viewtemplates/edit.js
- packages/saltcorn-data/base-plugin/viewtemplates/viewable_fields.js
- packages/saltcorn-data/models/page.ts
- packages/saltcorn-data/models/view.ts
- packages/saltcorn-markup/form.ts
- packages/saltcorn-mobile-app/www/index.html
- packages/saltcorn-mobile-app/www/js/mocks/request.js
- packages/saltcorn-mobile-app/www/js/routes/page.js
- packages/saltcorn-mobile-app/www/js/routes/view.js
- packages/saltcorn-mobile-app/www/js/utils/global_utils.js
- packages/saltcorn-mobile-app/www/js/utils/iframe_view_utils.js
- packages/server/public/saltcorn-common.js
- packages/server/public/saltcorn.js
- packages/server/routes/api.js
- allways set the form action, decide later if it should be printed
> mobile button actions

- .github/workflows/build_docs.yml
should fix the Documentation CI job
> increase max memory size of V8's old memory section

- packages/saltcorn-admin-models/models/pack.ts
- always reload existing plugins, '@saltcorn/ckeditor' for example installs '@saltcorn/html' as well
- causes trouble for webpack
> insert no plugin duplicates

- packages/saltcorn-mobile-app/www/index.html
- packages/saltcorn-mobile-app/www/js/utils/table_utils.js
- packages/saltcorn-mobile-builder/src/commands/build-app.ts
- wait until a bundle exports an object to window.saltcorn
just to be sure it really executed
- support exported headers as object and function
- local db update fix
- load packages without content delivery network
- Promise.all() fix
> mobile-app and mobile-builder fixes

- package-lock.json
- packages/db-common/sqlite-commons.ts
- packages/saltcorn-data/db/state.ts
- packages/saltcorn-data/mobile-mocks/saltcorn/html-pdf-node.ts
- packages/saltcorn-data/package.json
- packages/saltcorn-data/webpack.config.js
- packages/sqlite-mobile/sqlite-cordova.ts
- packages/sqlite/sqlite.ts
- moved sqlite functions to common
- mock deps for page-to-pdf
- no i18n init
> common mobile fixes

- package-lock.json
- packages/saltcorn-data/webpack.config.js
> fixed webpack build error

- packages/postgres/postgres.js
- packages/saltcorn-data/db/connect.js
- packages/saltcorn-data/models/user.ts
- packages/saltcorn-mobile-builder/utils/common-build-utils.ts
- packages/saltcorn-mobile-builder/utils/cordova-build-utils.ts
- packages/server/auth/routes.js
- added list tables functions in postgres.js
- last_mobile_logout with isostring
- create the app sqlite db with a separate process (force sqlite)
> support building app from a postgres db

- packages/saltcorn-mobile-builder/docker/post-installer.bash
- packages/saltcorn-mobile-builder/docker/post-installer.js
- packages/saltcorn-mobile-builder/package.json
- replaced the bash script with a .js file
- works on windows, too
> platform independent js script instead of bash

- .github/workflows/build_docs.yml
- README.md
- packages/saltcorn-data/models/config.ts
- packages/saltcorn-data/models/view.ts
- packages/saltcorn-mobile-app/www/index.html
- packages/saltcorn-mobile-app/www/js/routes/auth.js
- packages/saltcorn-mobile-app/www/js/routes/common.js
- packages/saltcorn-mobile-app/www/js/routes/delete.js
- packages/saltcorn-mobile-app/www/js/routes/edit.js
- packages/saltcorn-mobile-app/www/js/routes/page.js
- packages/saltcorn-mobile-app/www/js/routes/view.js
- packages/saltcorn-mobile-app/www/js/utils/global_utils.js
- packages/saltcorn-mobile-app/www/js/utils/iframe_view_utils.js
- packages/saltcorn-mobile-app/www/js/utils/table_utils.js
- packages/saltcorn-sbadmin2/index.js
- packages/saltcorn-types/base_types.ts
- packages/server/auth/routes.js
- update columns of replicated tables
- drop / rename columns is not supported on the admin interface, so it' not needed here
- continue as public user link on login
- role checks for local actions
> Mobile schema and public user

- packages/saltcorn-data/tests/tag.test.ts
- added await
- the tests are doing a lot db operations in the same it()
could lead to timeouts
> increased jest timeout

- packages/saltcorn-data/base-plugin/viewtemplates/listshowlist.js
- packages/saltcorn-data/diagram/cy_generate_utils.ts
- packages/saltcorn-data/diagram/cy_raster.ts
- packages/saltcorn-data/diagram/node.ts
- packages/saltcorn-data/diagram/node_extract_utils.ts
- packages/saltcorn-data/models/trigger.ts
- packages/saltcorn-types/base_types.ts
- packages/server/markup/admin.js
- packages/server/routes/diagram.js
- packages/server/routes/tags.js
- show table on top of views and to the left if there are multiple nodes
- show subtables of listshowlist in the embedded subviews
- added filter for views/pages/tables
> Diagram tables and filter

- packages/saltcorn-data/base-plugin/fileviews.js
- packages/saltcorn-data/base-plugin/viewtemplates/edit.js
- packages/saltcorn-data/models/file.ts
- packages/saltcorn-data/webpack.config.js
- packages/saltcorn-markup/layout.ts
- packages/saltcorn-mobile-app/www/js/utils/iframe_view_utils.js
- packages/saltcorn-mobile-builder/utils/common-build-utils.ts
- packages/server/locales/en.json
- packages/server/routes/admin.js
- packages/server/routes/api.js
- fixed images, file uploads and links for file folders
- fixes and more detailed debug logs
> Mobile app fixes

- packages/saltcorn-mobile-app/package.json
- packages/saltcorn-mobile-builder/docker/Dockerfile
- packages/saltcorn-mobile-builder/docker/entry.bash
- packages/saltcorn-mobile-builder/utils/cordova-build-utils.ts
- packages/server/public/saltcorn.js
run container with --network none
> Mobile app offline plugins

- packages/saltcorn-data/diagram/cy_generate_utils.ts
- packages/saltcorn-data/diagram/node_extract_utils.ts
- packages/saltcorn-data/diagram/nodes/dummy_node.ts
- packages/saltcorn-data/diagram/nodes/node.ts
- packages/saltcorn-data/diagram/nodes/page_node.ts
- packages/saltcorn-data/diagram/nodes/table_node.ts
- packages/saltcorn-data/diagram/nodes/trigger_node.ts
- packages/saltcorn-data/diagram/nodes/view_node.ts
- packages/saltcorn-data/models/view.ts
- packages/server/public/diagram_utils.js
- packages/server/public/saltcorn.css
- packages/server/routes/page.js
- packages/server/routes/view.js
- show a preview under a div overlay
- the overlay is transparent with a bold rotated 'preview' label
- added a rudinmental preview service for pages, a service for views was already there
> added previews on page and view cards

- packages/saltcorn-data/models/view.ts
- packages/saltcorn-mobile-app/www/index.html
- packages/saltcorn-mobile-app/www/js/routes/auth.js
- packages/saltcorn-mobile-app/www/js/utils/global_utils.js
- packages/saltcorn-mobile-app/www/js/utils/iframe_view_utils.js
- packages/saltcorn-mobile-app/www/js/utils/table_utils.js
- packages/saltcorn-types/base_types.ts
- packages/server/app.js
- packages/sqlite-mobile/sqlite-cordova.ts
- don't store the JSON Web Token in local storage use 'jwt_table' in the sqlite db
> replaced localstorage with sqlite

- packages/saltcorn-data/models/tag.ts
- packages/saltcorn-data/models/trigger.ts
- packages/server/locales/ru.json
- packages/server/public/diagram_utils.js
- packages/server/routes/diagram.js
- packages/server/routes/tag_entries.js
- packages/server/routes/tags.js
1. Add more i18 translations
2. Update Russian translation
3. Unify trigger(s) related code and urls for tags with other entities (pages, etc...)
4. little changes to remove few warnings
> More internationalization & small changes (see description)

- packages/saltcorn-data/models/discovery.ts
- packages/saltcorn-data/tests/discover.test.ts
1. support of forgotten tables with FK to sc tables
2. fix problem with table names (sqlsanitize)
3. tests covering for discovery.ts (covers most improvements and logic)
> Discovery tables improvements:

- package.json
- packages/saltcorn-data/migrate.js
- packages/saltcorn-mobile-app/www/js/mocks/request.js
- packages/saltcorn-mobile-app/www/js/routes/auth.js
- packages/saltcorn-mobile-app/www/js/routes/common.js
- packages/saltcorn-mobile-app/www/js/routes/delete.js
- packages/saltcorn-mobile-app/www/js/routes/edit.js
- packages/saltcorn-mobile-app/www/js/routes/error.js
- packages/saltcorn-mobile-app/www/js/routes/init.js
- packages/saltcorn-mobile-app/www/js/routes/page.js
- packages/saltcorn-mobile-app/www/js/routes/view.js
- packages/saltcorn-mobile-app/www/js/utils/file_helpers.js
- packages/saltcorn-mobile-app/www/js/utils/global_utils.js
- packages/saltcorn-mobile-app/www/js/utils/iframe_view_utils.js
- packages/saltcorn-mobile-app/www/js/utils/table_utils.js
- packages/saltcorn-mobile-builder/webpack.config.js
- the mobile app uses many globals included via script tag
- I believe some code should move to saltcorn-data so that it can be accessed via the global saltcorn property
> eslint errors in mobile-app and builder

- packages/saltcorn-data/index.ts
- packages/saltcorn-data/package.json
- packages/saltcorn-data/web-mobile-commons.ts
- packages/saltcorn-data/webpack.config.js
- packages/saltcorn-mobile-app/www/js/routes/common.js
- packages/server/routes/admin.js
- packages/server/wrapper.js
- show extra menus configured from 'settings / site structure / menu'
- disabled 'Link', 'Action' and 'Search' menu items
- added more webpack aliases to repair the webpack build step
> show extra menus, webpack cfg fixes

- packages/saltcorn-data/package.json
- packages/saltcorn-data/utils.ts
- packages/saltcorn-data/webpack.config.js
- packages/saltcorn-mobile-builder/utils/common-build-utils.ts
- packages/server/routes/admin.js
- spawn via full path if 'saltcorn' is not in PATH
- assert fallback for webpack
> Safe saltcorn cmd

- packages/saltcorn-cli/src/commands/build-app.js
- in multitenant mode, the user cannot be found outside of runWithTenant()
> load the user in runWithTenant

- packages/saltcorn-data/diagram/cy_generate_utils.ts
- packages/saltcorn-data/diagram/node_extract_utils.ts
- packages/saltcorn-data/diagram/nodes/node.ts
- packages/saltcorn-data/diagram/nodes/trigger_node.ts
- packages/server/public/diagram_utils.js
- a virtual trigger has no getTags() or db id
> virtual triggers in the diagram

- packages/saltcorn-data/base-plugin/actions.js
- packages/saltcorn-data/base-plugin/types.js
- packages/saltcorn-data/models/table.ts
also, preFormatted is pre-wrap
> modify_row action

- packages/saltcorn-data/base-plugin/actions.js
- packages/saltcorn-data/models/email.ts
- packages/saltcorn-data/models/table.ts
- added 'attachment_path' cfg variable to the send_email action
- the cfg is either a file field of the table, or points to a aggregation relation (for multiple attachments)
> added email attachments

- packages/saltcorn-data/models/trigger.ts
> Allow to catch any channel with empty channel field in _sc_triggers (#1723)

- packages/saltcorn-mobile-builder/mobile-builder.ts
- packages/saltcorn-mobile-builder/utils/package-bundle-utils.ts
- loadAllPlugins into the state class and use this to copy all needed files from the public directory over to the app
- when a header has the version number in it, create a directory for that
- subdirectories from the public folder are copied, too
> use state to copy files from plugins, headers with version number

- packages/saltcorn-cli/src/commands/take-snapshot.js
> New cli option for take-snapshot

- packages/saltcorn-data/base-plugin/viewtemplates/show.js
- packages/saltcorn-data/web-mobile-commons.ts
- packages/saltcorn-mobile-app/www/index.html
- packages/saltcorn-mobile-app/www/js/routes/api.js
- packages/saltcorn-mobile-app/www/js/routes/common.js
- packages/saltcorn-mobile-app/www/js/routes/delete.js
- packages/saltcorn-mobile-app/www/js/routes/init.js
- packages/saltcorn-mobile-app/www/js/utils/global_utils.js
- packages/saltcorn-mobile-app/www/js/utils/iframe_view_utils.js
- packages/saltcorn-mobile-app/www/js/utils/table_utils.js
- packages/server/public/saltcorn-common.js
- packages/server/public/saltcorn.css
- packages/server/routes/api.js
- edit-on-click for show views on mobile
- insert a user row on login into the db
- close navbar on click
- fixed redirects problems
> inline-edit, user row, redirects

- packages/saltcorn-data/models/table.ts
- packages/saltcorn-markup/layout.ts
- packages/saltcorn-mobile-app/www/js/utils/iframe_view_utils.js
- packages/saltcorn-mobile-app/www/js/utils/offline_mode_helper.js
- packages/saltcorn-mobile-app/www/js/utils/table_utils.js
- in deleteRows() check if the table has a primary key before resetting the seq
- in updateScTables() pick fields that really exist in the sqlitedb
> reset sequence, check existing cols

- Dockerfile.mobile.release
- set cordova version
- add plugins
> updated mobile docker release file

- packages/server/routes/fields.js
> skip the default edit for primary keys

- packages/saltcorn-mobile-app/www/index.html
- packages/saltcorn-mobile-app/www/js/routes/api.js
- packages/saltcorn-mobile-app/www/js/routes/common.js
- packages/saltcorn-mobile-app/www/js/routes/init.js
- packages/saltcorn-mobile-app/www/js/utils/file_helpers.js
- packages/saltcorn-mobile-builder/mobile-builder.ts
- packages/saltcorn-mobile-builder/utils/common-build-utils.ts
- packages/saltcorn-types/base_types.ts
- the builder reads the logo file as base64 and adds it to the www directory
-  the app adds the base64 string in its layout wrap call
> site logo on mobile

- .gitignore
- packages/db-common/internal.test.js
- packages/db-common/internal.ts
Rewrite jsonWhere (closes #1941 also closes #1896)
> Rewrite jsonWhere (closes #1941, closes #1896)

- packages/saltcorn-cli/src/commands/info.js
- packages/saltcorn-cli/src/commands/install-pack.js
- packages/saltcorn-cli/src/commands/list-tenants.js
- packages/saltcorn-cli/src/commands/list-users.js
- packages/saltcorn-cli/src/common.js
1. add new CLI command list-users.
2. add json output fo few CLI commands.
> Add new CLI command list-users.

- packages/saltcorn-data/base-plugin/viewtemplates/filter.js
- packages/saltcorn-data/models/table.ts
- packages/saltcorn-mobile-app/www/js/mocks/request.js
- packages/saltcorn-mobile-app/www/js/routes/view.js
- packages/saltcorn-mobile-app/www/js/utils/global_utils.js
- packages/saltcorn-mobile-app/www/js/utils/iframe_view_utils.js
- packages/saltcorn-mobile-app/www/js/utils/table_utils.js
- packages/server/public/saltcorn-common.js
multi-actions on mobile and in the offline mode
> multi-actions on mobile

- deploy/pupchecks/no_fixtures/blog_pack.pch
- packages/saltcorn-markup/index.ts
- packages/saltcorn-markup/layout.ts
- packages/saltcorn-markup/layout_utils.ts
- packages/saltcorn-mobile-app/www/index.html
- packages/saltcorn-mobile-app/www/js/routes/common.js
- packages/saltcorn-mobile-app/www/js/utils/global_utils.js
- packages/saltcorn-mobile-app/www/js/utils/iframe_view_utils.js
- packages/saltcorn-sbadmin2/index.js
- packages/server/public/saltcorn-common.js
- packages/server/routes/admin.js
- packages/server/routes/viewedit.js
- packages/server/tests/table.test.js
- the function signatures still uses alert but now it gets mapped to a toast function
- alerts-area is deprecated, but for now still there
> migrated the alert messages to toasts

- packages/saltcorn-cli/.gitignore
- packages/saltcorn-cli/package.json
- packages/saltcorn-cli/src/commands/dev/plugin-test.js
- packages/saltcorn-cli/src/common.js
- packages/saltcorn-data/tsconfig.json
- packages/saltcorn-data/webpack.config.js
- packages/server/load_plugins.js
- install a plugin, do 'npm run test' in the install directory and check the return code
- the plugin can have a backup file with test data the backup can be restored once with the cli command for all tests or from the test file with prep_test_db()
> plugin testing cli tool

- packages/server/routes/tables.js
> Separate label from value for "Database table" in provider_name

- packages/saltcorn-data/plugin-helper.js
...if there are external tables or tables from provider plugins
> Fix error in /diagram: TypeError: table.getTags is not a function

- packages/saltcorn-data/models/table.ts
- packages/saltcorn-data/web-mobile-commons.ts
- packages/saltcorn-mobile-app/www/index.html
- packages/saltcorn-mobile-app/www/js/mocks/request.js
- packages/saltcorn-mobile-app/www/js/mocks/response.js
- packages/saltcorn-mobile-app/www/js/routes/fields.js
- packages/saltcorn-mobile-app/www/js/routes/init.js
- packages/saltcorn-mobile-app/www/js/utils/global_utils.js
- packages/saltcorn-mobile-app/www/js/utils/iframe_view_utils.js
- packages/server/public/saltcorn-common.js
- show calculated joinFields on mobile
- delete fix for sync_info
- no_submit_reload on modals flag
- show calculated joinFields cache hit update
> show calculated joinFields on mobile

- packages/saltcorn-data/base-plugin/types.js
- perhaps we should ensure that it's always Date
> in sqlite mode Date can be number

- packages/saltcorn-cli/src/commands/dev/plugin-test.js
- the live-plugin-manager knows how to handle dependencies in 'plugin_packages' but jests does not
- add a modulePath to the package.json, so that dependencies from the plugin can be resolved in jest
> jest modulePaths for dynamic deps in jest

- packages/saltcorn-data/utils.ts
- packages/server/routes/page.js
- packages/server/routes/view.js
- sometimes the jest enviroment closes before this runs
> no setTimeout block in unit tests

- packages/saltcorn-data/plugin-helper.js
- packages/saltcorn-data/tests/auxtest.test.ts
- packages/saltcorn-data/tests/common_helpers.ts
- packages/server/locales/en.json
- packages/server/tests/view.test.js
- for now without levels, only with a many-to-many join table
> support many-to-many relations in the picker

- packages/db-common/internal.ts
> set inColumn when there is only one joinLevel

- package-lock.json
- packages/saltcorn-data/base-plugin/viewtemplates/edit.js
- packages/saltcorn-data/base-plugin/viewtemplates/viewable_fields.js
- packages/saltcorn-data/db/fixtures.js
- packages/server/tests/view.test.js
- ChildList with one/two layers works again
- build a view_select that looks like from a normal ChildList
> fixed edit-in-edit with relation paths

- packages/saltcorn-data/base-plugin/viewtemplates/edit.js
- packages/saltcorn-data/db/fixtures.js
- packages/saltcorn-data/tests/auxtest.test.ts
- packages/saltcorn-data/tests/view.test.ts
- packages/server/auth/testhelp.js
- packages/server/tests/view.test.js
- don't crash for empty query, use relationTypeFromPath() and make the subview blank
> edit-view with embedded show

- packages/saltcorn-admin-models/models/backup.ts
- packages/saltcorn-data/migrate.js
We may want this in the future
> Write completed migrations to backup file

- packages/saltcorn-admin-models/models/pack.ts
- packages/saltcorn-admin-models/tests/pack.test.ts
- packages/saltcorn-data/migrations/202402071125.js
- packages/saltcorn-data/models/page_group.ts
- packages/saltcorn-types/model-abstracts/abstract_page_group.ts
- packages/server/locales/en.json
- packages/server/routes/page.js
- packages/server/routes/page_groupedit.js
- packages/server/routes/utils.js
- packages/server/tests/page_group.test.js
- hash the sessionID and use modulo to make it an index
- seems to work better with pq session ids than for sqlite, and with more members than just two
- perhaps the randomness can be improved
> option to send a random page, depending on the session id

- package-lock.json
- packages/plugins-loader/plugin_installer.js
- packages/saltcorn-mobile-builder/utils/package-bundle-utils.ts
- fix for #2410 
- don't fail building with the summernote plugin
> rename fallback to copy, warn missing headers

- packages/saltcorn-data/base-plugin/types.js
Dynamic calculation of the inner text color for a clear contrast
> heat_cell: adapt text colour to background colour luminance

- README.md
- packages/saltcorn-cli/src/commands/serve.js
- packages/saltcorn-data/models/config.ts
- packages/server/app.js
- packages/server/auth/admin.js
- packages/server/locales/en.json
- packages/server/public/log_viewer_utils.js
- packages/server/routes/tenant.js
- packages/server/routes/utils.js
- packages/server/serve.js
to close things in with the random logout problem
> pruneSessionInterval flag, log viewer improvements

- packages/saltcorn-data/models/config.ts
- packages/server/auth/routes.js
- changed cookie_duration default (without remember)
- use 720 hours default when nothing is set
- use maxAge for loggein cookie
> cookie_duration default, loggedin maxAge

- packages/saltcorn-admin-models/package.json
- packages/saltcorn-cli/src/commands/dev/release.js
- packages/saltcorn-data/package.json
- packages/saltcorn-random-tests/package.json
- packages/saltcorn-types/package.json
needs an update on chaos-guinea-pig to 0.1.6
> prepared release fix

- packages/saltcorn-data/base-plugin/fileviews.js
- packages/server/public/saltcorn.css
- allow to select a button class and a label for input file
> custom buttons for file uploads

- packages/saltcorn-data/db/state.ts
> Version npm code pkgs

- packages/server/routes/admin.js
- default is false and you have to activate it everytime when you want to clean
- not on upgrade
- it's more for not having to use SSH to do this https://wiki.saltcorn.com/view/ShowPage/troubleshooting  (Directory not empty error during upgrade)
see #2662
> clean node_modules checkbox on install a fixed sc version

- packages/saltcorn-data/db/state.ts
- packages/saltcorn-data/migrate.js
- packages/saltcorn-data/utils.ts
- packages/server/load_plugins.js
- only open transactions if needed in migrate
- keepUnchanged flag in refresh state
> small startup speedup for system with many tenants

- packages/saltcorn-mobile-app/www/js/utils/global_utils.js
or you get stuck in an invalid app state
> replace the modal body when the response is html content

- packages/saltcorn-mobile-app/www/index.html
- packages/saltcorn-mobile-app/www/js/utils/iframe_view_utils.js
- packages/server/public/saltcorn-common.js
- packages/server/public/saltcorn.css
- youtube embeds markded with the 'mobile-youtube-video' attribute will open in the inAppBrowser on mobile
- the iframe will be replaced with an img thumbnail element
- added a lastLocation item to return to the original view when the inAppBrowser closes
> transform youtube embeds marked with 'mobile-youtube-video'

- packages/saltcorn-mobile-app/www/js/utils/iframe_view_utils.js
- gives you an exit button, otherwise there was only the back gesture
- seems to work only on ios
> open the inAppBrowser with a toolbar

- packages/saltcorn-mobile-builder/utils/cordova_helper.ts
- or building for ios throws ENOBUFS
> increase maxBuffer for build spawn and exec stdout

- packages/saltcorn-data/models/expression.ts
> uuid pagination problem in recalcStored

- package-lock.json
- packages/saltcorn-data/base-plugin/fieldviews.js
- packages/saltcorn-data/base-plugin/viewtemplates/edit.js
- packages/saltcorn-data/models/field.ts
- packages/saltcorn-types/model-abstracts/abstract_field.ts
- packages/server/public/saltcorn.js
- when a select loses it's focus, it creates an onchange on the form
- this could result in two change events (if you change the value), or if you just open and close the select, you get one change event without value changes
- #2758
> in saveAndContinue check if a select input has changed

- packages/saltcorn-data/base-plugin/fieldviews.js
- packages/saltcorn-data/base-plugin/viewtemplates/edit.js
- packages/saltcorn-data/db/fixtures.js
- packages/saltcorn-data/tests/view.test.ts
> check option without type

- packages/saltcorn-data/base-plugin/types.js
- packages/saltcorn-data/base-plugin/viewtemplates/edit.js
works with foreign keys, but we have the same problem here
related to #2758
> check select input has changed for strings with fixed options

- packages/server/locales/pl.json
Adding new translations to Polish
> polish translation update

- packages/saltcorn-data/base-plugin/types.js
- packages/saltcorn-data/base-plugin/viewtemplates/room.js
- packages/saltcorn-data/models/config.ts
- packages/saltcorn-data/models/page_group.ts
- packages/saltcorn-data/models/view.ts
- packages/saltcorn-data/tests/mocks.ts
- packages/saltcorn-markup/index.ts
- packages/server/locales/en.json
- packages/server/public/gridedit.js
- packages/server/routes/admin.js
- packages/server/routes/eventlog.js
- packages/server/routes/tenant.js
Set the default locale under About application
> Default locale

- packages/plugins-loader/download_utils.js
- packages/server/serve.js
- could overwrite the version of another tenant or the admin
- and causes sometimes 403 codes while downloading the tarball
> no force in tenants

- packages/server/locales/pl.json
> update polish translation

- packages/server/public/saltcorn.js
- packages/server/tests/clientjs.test.js
Fixes #2946 by adding function `addQueryStringParameter`, which and slightly extending `removeQueryStringParameter` to remove specific parameter-value-pair.
> Fix query string build on check_state_field

- packages/saltcorn-markup/tags.ts
- sometimes we need to keep specific attributes
> custom whitelist for text tags

- packages/saltcorn-data/models/config.ts
- packages/saltcorn-markup/index.ts
- packages/saltcorn-mobile-app/src/helpers/common.js
- packages/saltcorn-mobile-app/src/init.js
- packages/saltcorn-mobile-app/src/routing/index.js
- packages/saltcorn-mobile-app/src/routing/routes/notifications.js
- packages/saltcorn-mobile-app/src/routing/utils.js
- packages/saltcorn-mobile-app/webpack.config.js
- packages/saltcorn-mobile-builder/mobile-builder.ts
- packages/saltcorn-mobile-builder/utils/capacitor-helper.ts
- packages/saltcorn-mobile-builder/utils/common-build-utils.ts
- packages/server/routes/admin.js
- packages/server/routes/notifications.js
- packages/server/tests/api.test.js
- show a basic menu with the share result for some seconds
- it's another activity, so just close it after the share
> sendIntent activity on android for sharing

- packages/plugins-loader/plugin_installer.js
- packages/server/serve.js
- remove plugin folders with missing node_modules dir
- only when there are dependencies that should be installed
- the PluginInstaller creates it new later
- minimal logs, here the loglevel is still on 1
> ensure plugins folder on startup

- packages/saltcorn-data/db/state.ts
- packages/saltcorn-data/webpack.config.js
- packages/saltcorn-mobile-builder/tests/webpack.test.ts
- codeNPMmodules aren't supported on mobile yet
> remove webpack warnings for dynamic require

- packages/saltcorn-cli/package.json
- for installs from npm instead of the dev checkout
> overrides in cli package.json

- packages/saltcorn-cli/src/commands/dev/translate.js
- packages/saltcorn-data/base-plugin/viewtemplates/edit.js
- packages/saltcorn-data/base-plugin/viewtemplates/filter.js
- packages/saltcorn-data/base-plugin/viewtemplates/list.js
- packages/saltcorn-data/base-plugin/viewtemplates/show.js
- packages/saltcorn-data/plugin-helper.js
- packages/saltcorn-markup/form.ts
- packages/server/app.js
- packages/server/help/index.js
- packages/server/locales/en.json
- packages/server/routes/actions.js
- packages/server/routes/admin.js
- packages/server/routes/fields.js
- packages/server/routes/pageedit.js
for examples, see bash and tinymce modules
> Modules: Help and translations

- packages/saltcorn-mobile-builder/utils/capacitor-helper.ts
- packages/server/public/saltcorn.js
- needed for the docker stdandard mode
- otherwise, some files are owned by root and the second build fails because of permission problems
> added user flag for docker run

- packages/saltcorn-markup/layout_utils.ts
- packages/saltcorn-sbadmin2/index.js
- packages/server/tests/menu.test.js
- instead of startsWith, use a ReqEx
- #2952
> active menu highlight problem

- packages/server/public/saltcorn-common.js
> for nested forms, get the form via event.srcElement

- packages/saltcorn-data/base-plugin/actions.js
- packages/saltcorn-data/base-plugin/viewtemplates/edit.js
- packages/server/public/saltcorn-common.js
- packages/server/public/saltcorn.js
- not implemented for SaveAndContinue, and I believe there is more what the normal POST upload does, which is missing here
- #2932
> Save form_actions with file fields use multipart/form-data

- packages/server/app.js
- packages/server/routes/view.js
- needed to hide the editbar when a react view loads a normal saltcorn view
> added rvr flag for requests coming from a react view

- packages/server/routes/tenant.js
Fix as described in issue #3090
> #3090 fix url composition for better multi-tenant support

- packages/saltcorn-data/base-plugin/actions.js
- packages/saltcorn-data/models/email.ts
- packages/server/routes/admin.js
> smtp-username, gmail params, false for empty accepted

- packages/db-common/internal.ts
> only use websearch_to_tsquery if there is a space in search term  (to allow partial match)

- packages/saltcorn-types/base_types.ts
- packages/server/app.js
- packages/server/plugin_routes_handler.js
- needed for example to use the react plugin on saltcorn.com
- react propably needs multi tenant support, too
- #3311
> mount plugin routes from the root and all sub tenants

- packages/server/locales/pt.json
PR to help with [this issue](https://github.com/saltcorn/saltcorn/issues/3327#issue-3115755621)
> Fix translation in pt.json

- README.md
- packages/saltcorn-mobile-builder/docker/entry.bash
- packages/server/routes/api.js
- packages/server/tests/api.test.js
- ensure it can be removed by the next run
- remove some no longer needed dirs
> full access to android platform dir, countRows endpoint

- packages/saltcorn-data/db/state.ts
- packages/saltcorn-data/models/config.ts
- packages/saltcorn-data/models/view.ts
- packages/server/public/saltcorn-common.js
- packages/server/serve.js
- each tenant has a _[tenant]_collab_room_ in the / namespace
- server-side  : view.ts has an emit function
- browser-side : saltcorn_common.js has an open socket function
expecting the required socket.io callbacks
#3273
> real time collaboration functions

- packages/saltcorn-data/base-plugin/viewtemplates/edit.js
- packages/server/public/saltcorn.js
- in saveAndContinue add an attribute to the input
- in the the realTime callback skip the input if the attr is set
> skip real-time update when the event comes from saveAndContinue

- deploy/playwright/Csv_file_to_uplaod/People2.csv
- deploy/playwright/pageobject/locators.js
- deploy/playwright/tests/TC_29_Action.spec.js
- deploy/playwright/tests/TC_30_toast_validation.spec.js
- deploy/playwright/tests/TC_31_filter_view.spec.js
Scripts for Action, Toast validation and filter
> Scripts for Action, Toast validation and filter

- packages/saltcorn-data/db/state.ts
- packages/saltcorn-data/models/config.ts
- packages/server/serve.js
> ephemeral flag for configs that should not persist

- packages/saltcorn-cli/src/commands/dev/plugin-test.js
- perhaps we should use ts-jest
> fixed the plugin-test cmd

- packages/saltcorn-mobile-app/src/init.js
- for headers that should not got into the iframe but the top scope of the index.html
- needed for rrweb of the record-and-rerun plugin
> mobile_top_scope flag

- packages/server/help/Calculated fields.tmd
- packages/server/help/Field types.tmd
- packages/server/help/Protected fields.tmd
During development encountered some basic typo's.
This is a basic PR with some fixes.
> Fix typo's in field documentation

- packages/db-common/sqlite-commons.ts
- packages/db-common/types.ts
- packages/postgres/postgres.js
- packages/saltcorn-data/models/table.ts
> do not fail for sync_info errors

- packages/postgres/postgres.js
- packages/saltcorn-admin-models/models/backup.ts
- packages/saltcorn-admin-models/models/pack.ts
- packages/saltcorn-admin-models/tests/backup.test.ts
- packages/saltcorn-data/models/config.ts
- packages/server/routes/admin.js
> Restore user table properties. Drop table constraints on clear-all

- packages/saltcorn-data/models/trigger.ts
- packages/saltcorn-types/base_types.ts
- packages/server/routes/actions.js
- show triggers when requireRow is explicit set to false
> actionsNotRequiring row in the page builder
