deploy/examples/test/docker-compose.yml
The existing docker file was a little confusing, I didn't realize you had to set the variables in an external .env file, I think it makes more sense to put it in the docker file directly, and import the env values, not the entire structure.  Also added a few quality of life improvements.  Since I am on v3.7 for docker-compose I used that version, but I believe it will work with older versions.
=> Update the docker-compose.yml

packages/saltcorn-mobile-app/www/js/utils/global_utils.js
- executes domready tags and the CKEditor will show up, but it should be generally useful, too
=> execute scripts within the page-inner-content div

deploy/docker-mobile-builder/Dockerfile
- create an empty cordova project while building the image
- gradle seems to download a lot of dependencies on the first init
=> speed up apk build in container

deploy/docker-mobile-builder/Dockerfile
- npm run changes the user, when run as root, and that user has no permissions for
/root/.config
=> permissions for npm run add-platform

packages/saltcorn-cli/src/commands/run-tests.js
- it seems the standard provider (babel) runs out of heap memory
even with really high max-old-space sizes (just takes a bit longer) or crashes hard
- the v8 provider seems to use way less memory
https://github.com/facebook/jest/issues/5837#issuecomment-622402792
=> switching to the v8 coverageProvider

packages/saltcorn-data/base-plugin/types.js
Table views showing a date column with the "format" field view were not properly localised, so e.g. week days were always in English. This PR fixes this by applying the locale configuration for this case as well.
=> fix formatted date not being localised

packages/saltcorn-cli/src/commands/build-app.js, packages/saltcorn-cli/src/commands/serve.js, packages/saltcorn-data/models/view.ts, packages/saltcorn-mobile-app/www/js/utils/global_utils.js, packages/saltcorn-mobile-app/www/js/utils/table_utils.js, packages/saltcorn-mobile-builder/mobile-builder.ts, packages/saltcorn-mobile-builder/utils/common-build-utils.ts, packages/server/app.js, packages/server/auth/routes.js, packages/server/routes/admin.js, packages/server/routes/utils.js
- added tenantAppName to the build-app cli to build for a specific tenant
- the mobile app sends the subdomain as a 'x-saltcorn-app' header
- the jwt strategy uses a tenant field of the token
=> multi_tenant mode in mobile-app

packages/saltcorn-mobile-app/package.json, packages/saltcorn-mobile-builder/docker/Dockerfile, packages/saltcorn-mobile-builder/docker/entry.bash, packages/saltcorn-mobile-builder/utils/cordova-build-utils.ts, packages/server/public/saltcorn.js
- removed cordova plugins from package.json and add them at build time
- a build without docker adds them the normal way and they are loaded from npm
- a docker build uses plugins that are already on disk
=> load cordova plugins via file reference in docker

packages/server/auth/routes.js
Set browser locale as active if user.language is not set yet. Otherwise, the default selection will always be English in the dropdown menu. As the form is saved on changes only, a user with a browser locale different than English has to select a different language first, before he can select and save English as language. This is quite inconvenient.
=> Set browser locale as active if user.language is not set yet

packages/saltcorn-cli/src/commands/set-cfg.js, packages/saltcorn-mobile-app/www/js/utils/global_utils.js, packages/saltcorn-mobile-app/www/js/utils/iframe_view_utils.js, packages/server/auth/routes.js
- use a jwt with roleid 10 for logins without email and password
- otherwise in multitenant mode, we land on the root app as public user
- init the tenant in 'set-cfg cli' if the parameter is set
=> public login on mobile, set cfg with multitenant

Dockerfile.mobile.release, deploy/docker_build_push.sh, packages/saltcorn-cli/src/commands/release.js, packages/saltcorn-cli/src/commands/setup.js, packages/saltcorn-mobile-builder/utils/cordova-build-utils.ts, packages/server/routes/admin.js
- the image has all depencies to build a mobile app for android and the '@saltcorn/cli' version from npm (like the release image)
- is needed because the image from 'saltcorn-mobile-builder' only has the build dependencies and it's complicated to run the build image from another container
- added NODE_ENV=development for the cordova commands it fails with NODE_ENV=production
=> docker image with saltcorn and mobile dependencies

packages/saltcorn-data/models/config.ts, packages/saltcorn-markup/builder.ts, packages/server/locales/en.json, packages/server/locales/fr.json, packages/server/public/saltcorn.js, packages/server/routes/admin.js, packages/server/routes/tenant.js, packages/server/s3storage.js, packages/server/wrapper.js
This removes the default file upload limit, because that limit is imposed on the initial upload of a backup to restore. File size limit is still available as an option (change base to kb)
=> Config: increase default upload size. log client errors option

packages/saltcorn-cli/bin/saltcorn
- inform the user but don't crash
- stack traces in TypeScript modules will point into the dist folder when the init fails
=> don't fail for source-map-support

deploy/vagrant-test-install/ubuntu2004-mobile/Vagrantfile
- the provision script uses most of the commands from the docker file in the mobile-builder pck
- run with 4 gb ram
- there is no initial project to cache the plugins
- call 'saltcorn install-pack' with "Address book"
- call saltcorn build-app
- all cli commands are run with 'sudo -u saltcorn' for 'build-app' we have to add a lot preserve-env variables
- fails with 'v0.8.1-rc.2' but should work with all never version
=> vagrant file for a mobile build on ubuntu 20.04

packages/saltcorn-data/tests/remote_query_helper.ts
- the remote query test called the server without a jwt
- happened because the jwt is now in mobileconfig instead of localstorage
=> init mobile cfg in view queries

deploy/vagrant-test-install/ubuntu2004-mobile-docker/Vagrantfile, packages/saltcorn-cli/src/commands/build-app.js, packages/saltcorn-cli/src/commands/build-cordova-builder.js, packages/saltcorn-mobile-builder/utils/cordova-build-utils.ts
- added a vagrant file that installs docker, adds saltcorn to the docker group and builds a mobile app with the saltcorn/cordova-builder docker image
- Normally, 'cordova-builder' is created while installing saltcorn but it failed because the new saltcorn user wasn't allowed to access docker
- as a workaround, the vagrant file re-builds the image manually
=> vagrant test and cli command to build the cordova-builder

packages/saltcorn-data/models/field.ts, packages/saltcorn-data/tests/exact_views.test.ts, packages/saltcorn-markup/layout.ts, packages/saltcorn-mobile-app/www/index.html, packages/saltcorn-mobile-app/www/js/routes/auth.js, packages/saltcorn-mobile-app/www/js/utils/global_utils.js, packages/server/public/saltcorn.js
- redirects starting with http://localhost are meant for the entrypoint
- links to pages
- don't fail for versioned tables (disable them for now on mobile)
- empty the routing history on logout the back button closes the app on the login view
=> redirect, links and versioned tables on mobile

packages/saltcorn-cli/src/commands/build-cordova-builder.js, packages/saltcorn-mobile-app/www/index.html, packages/saltcorn-mobile-app/www/js/utils/table_utils.js, packages/saltcorn-mobile-builder/docker/Dockerfile
- for now, don't use the newest cordova major version (12)
- keep empty string while updating the db
- added an option to build the 'cordova-builder' from scratch via the saltcorn cli
=> cordova version, empty strings, build clean option

packages/saltcorn-data/migrations/202304281224.js, packages/saltcorn-data/models/file.ts, packages/saltcorn-data/models/workflow.ts, packages/server/routes/files.js, packages/server/routes/viewedit.js
- added caching for allDirectories() so that you don't have to recalc it so often
- only for builder steps, and destroy it as soon as possible
=> dirCache for builder workflowSteps

packages/saltcorn-markup/layout.ts
fix for #1859 
set 'mobile-img-path' so that it gets loaded
=> set mobile-img-path attribute

package-lock.json, packages/server/package.json, packages/server/public/relationship_diagram_utils.js, packages/server/routes/tables.js
- removed the mermaid cli dependency (pupeteer is too large):
https://github.com/saltcorn/saltcorn/issues/635#issuecomment-1652254676
- export the diagram as svg without the server (the background is transparent)
=> export erd browserside as svg without cli

deploy/vagrant-test-install/debian11-mobile/Vagrantfile, deploy/vagrant-test-install/test_all.sh, deploy/vagrant-test-install/ubuntu2004-mobile/Vagrantfile, packages/saltcorn-mobile-builder/appium_tests/package.json, packages/saltcorn-mobile-builder/appium_tests/ui.test.js, packages/saltcorn-mobile-builder/package.json, packages/saltcorn-mobile-builder/tests/webpack.test.ts, packages/saltcorn-mobile-builder/utils/common-build-utils.ts, packages/saltcorn-types/base_types.ts
- Vagrant tests with an Android emulator and appium for the ui tests
- libvirt is required as provider, and the machines need a lot of RAM.
- The appium tests are in the mobile-builder package, and the vagrant machine copies those files into its file system.
- It takes some time until the emulator is ready to install apks. So I added a long wait.
- The appium tests are rudimental, but if that works, we can write more of them.
=> Mobile build tests

packages/saltcorn-cli/src/commands/build-app.js, packages/saltcorn-data/models/view.ts, packages/saltcorn-data/utils.ts, packages/saltcorn-markup/layout.ts, packages/saltcorn-mobile-app/config.xml, packages/saltcorn-mobile-app/www/index.html, packages/saltcorn-mobile-app/www/js/utils/iframe_view_utils.js, packages/saltcorn-mobile-app/www/js/utils/offline_mode_helper.js, packages/saltcorn-mobile-builder/mobile-builder.ts, packages/saltcorn-mobile-builder/utils/common-build-utils.ts, packages/saltcorn-types/base_types.ts, packages/server/locales/en.json, packages/server/public/saltcorn.js, packages/server/routes/admin.js, packages/server/routes/sync.js, packages/server/tests/sync.test.js
- onclick handler for cards and container
- plugin selector for modules that should be included into the build
- check ownership field of the synched rows
- add a wackelock while synching
- shutting down the app or phone while synching blocks the offline mode until the next sync
- only do a automatic public login when the new 'auto public login' checkbox is clicked, otherwise it could result in too many sync calls
=> mobile onclicks, plugin-selector, sync ownership, wakelock, auto public login

packages/server/routes/menu.js
Especially useful with [config-tables](https://github.com/pyhedgehog/saltcorn-config-tables) plugin. 😃
=> Allow to use external tables in dynamic menu entries

packages/saltcorn-cli/src/commands/build-app.js, packages/saltcorn-data/tests/exact_views.test.ts, packages/saltcorn-markup/layout.ts, packages/saltcorn-mobile-app/www/js/utils/iframe_view_utils.js, packages/server/auth/routes.js, packages/server/routes/admin.js
- open links with an URL source in the system browser on mobile
- restore the entryPointType in the builder menu as well
- use site name in public welcome
- try empty strings in login and let it fail
=> mobile links, restore entryPointType, improvements

packages/saltcorn-cli/src/commands/sync-upload-data.js, packages/saltcorn-data/base-plugin/viewtemplates/edit.js, packages/saltcorn-data/models/field.ts, packages/saltcorn-data/models/table.ts, packages/saltcorn-mobile-app/www/index.html, packages/saltcorn-mobile-app/www/js/utils/offline_mode_helper.js, packages/saltcorn-mobile-app/www/js/utils/table_utils.js, packages/saltcorn-mobile-builder/utils/common-build-utils.ts, packages/server/routes/sync.js, packages/server/tests/sync.test.js
- when a unique constraint fires while syncing, translate to the existing row
- faster startup after the first installation
- skip local files
=> handle constraints, no crash for files, optimize startup on mobile

Dockerfile.dev
I'm using this patch (as a sed command in gitlab build job) for long time.
=> Make `saltcorn` command available in path in Dockerfile.dev

packages/saltcorn-data/base-plugin/viewtemplates/edit.js, packages/saltcorn-data/models/file.ts, packages/saltcorn-data/models/view.ts, packages/saltcorn-types/base_types.ts, packages/server/serve.js
- socket-io interface for the Recorder plugin
- should work for other stream targets, too, but right now only fileviews are checked
- there is only a method to open and return the stream
- the caller can do the writing and closing otherwise we would have to do all the fetching for every stream operation
=> stream-interface to write into the view of a table field

package-lock.json, packages/plugins-loader/package.json, packages/plugins-loader/plugin_installer.js
- when plugins are loaded in a directory where the recursive module loading is not possible @saltcorn/data and @saltcorn/markup can't be resolved
- added a symlink on top of the plugins-folder directory for that
=> symlink into the saltcorn node_modules dir for plugins

package-lock.json, package.json, packages/saltcorn-data/mobile-mocks/copy_excluded_files.js, packages/saltcorn-data/mobile-mocks/node/vm.js, packages/saltcorn-data/package.json, packages/saltcorn-data/tsconfig.json, packages/saltcorn-data/webpack.config.js, packages/saltcorn-mobile-app/www/js/utils/global_utils.js
- stop all scripts running in the iframe via clearing the innerHTML before navigation
- sometimes the navigation only starts after all scripts on the current page are done, even if we want to leave this page
- [vm-browserify](https://www.npmjs.com/package/vm-browserify) creates an iframe for every expression call to isolate the code
- has a large impact when there are many extra-state-formulas
- added iframe caching, based on a pr that was already there but not merged
=> clear inner-content-div, cache iframe of browser vm

packages/server/routes/notifications.js, packages/server/wrapper.js
- caching in the mobile android chrome browser can cause confusion especially for the admin
=> no cache for the manifest if its the admin

packages/plugins-loader/stable_versioning.js, packages/saltcorn-admin-models/models/tenant.ts, packages/saltcorn-cli/src/commands/plugins.js, packages/saltcorn-data/db/state.ts, packages/saltcorn-data/models/config.ts, packages/saltcorn-data/models/plugin.ts, packages/server/load_plugins.js, packages/server/routes/plugins.js, packages/server/serve.js
- added two configurations to cache the enigne infos
- 'engines_cache' caches engine infos of plugins 
- 'engines_cache_sc_version' stores the version with which the cache was build
- changed State.setConfig so that you can set a config on the root state from a tenant
=> cache the plugin engine infos, reload when the sc version changes

packages/server/locales/en.json, packages/server/routes/admin.js
- 1. check characters and format of only the build dir name
- 2. resolve full buildDir path and check it starts with ${rootFolder.location}/mobile_app
=> validate mobile-app-result build dir

packages/server/load_plugins.js, packages/server/routes/plugins.js
- when a plugin gets a new version it's not in the cache until the sc version changes
- added a force fetch retry
- #2735
=> try force fetch when a plugin version is not in the cache

packages/install/index.js, packages/install/utils.js
- when the prefix is set in the current process, the old prefix is still in the enviroment
- when the install script creates the docker group, we have to spawn docker with newgrp to see the group without relogin
=> npm_prefix on spawn npm, apply fresh docker group

packages/saltcorn-mobile-app/www/js/utils/iframe_view_utils.js
- _blank opens a new standalone inAppBrowser instead of replacing the current view
- _system could propably handle more files, but this is the system browser and we can get conflicts with the connect.sid session
- I guess we should change this after v 1.0
=> encode filename and open inAppBrowser with _blank

packages/server/routes/api.js, packages/server/tests/api.test.js
This provides an API to serve files using the bearer token or access token in the query string
`/api/serve-files/{path/to/file}`
=> API to serve files with bearer token

packages/saltcorn-data/base-plugin/actions.js
=> Fix `sync_table_from_external` to use tables with provider_name as source

packages/saltcorn-data/db/state.ts, packages/saltcorn-mobile-app/build_scripts/modify_android_manifest.js, packages/saltcorn-mobile-app/src/helpers/common.js, packages/saltcorn-mobile-app/src/index.js, packages/saltcorn-mobile-builder/docker/Dockerfile, packages/saltcorn-mobile-builder/docker/entry.bash, packages/saltcorn-mobile-builder/mobile-builder.ts, packages/saltcorn-mobile-builder/utils/capacitor-helper.ts, packages/saltcorn-mobile-builder/utils/common-build-utils.ts, packages/saltcorn-mobile-builder/utils/package-bundle-utils.ts, packages/saltcorn-types/base_types.ts
- a plugin can specify which capacitor plugins are needed
- a plugin can have a mobile-app dir with esm code that will be bundled into the app index.js has to be the entry point
=> capacitor plugins array in saltcorn plugins and mobile code dir

packages/saltcorn-data/db/state.ts
- the live-plugin-manager returns {}
- propably because it's a build in
- #3233
=> allow v8 in run_code, when enabled in the dev settings

packages/saltcorn-data/models/config.ts, packages/server/serve.js
- removed engines cache version and no clear cache on version mismatch
- don't clear the cache on startup after saltcorn was updated
- #3465
=> no clear engines cache after upgrade

packages/plain-date/package.json
Including necessary build files in plain-date package.json
=> including dist directory over npmignore
